1D array

In [1]:
import numpy as np

## create array using numpy
## create 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


2D array

In [2]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row 5 columns

array([[1, 2, 3, 4, 5]])

In [3]:
arr3 = np.array([[1,2,3,4,5]])
print(arr3.shape)

(1, 5)


In [4]:
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


Creating array using inbuilt menthods

In [5]:
np.arange(0,10,2).reshape(5,1) # 5 rows and 1 column

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Example - Attributes of Numpy

In [8]:
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape:", arr.shape)
print("Number of Dimensions:", arr.ndim)
print("Size (number of elements):", arr.size)
print("Data Type:", arr.dtype)
print("Item size (in bytes):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of Dimensions: 2
Size (number of elements): 6
Data Type: int32
Item size (in bytes): 4


Numpy Vectorized Operations

In [9]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# element wise addition
print("Addition: ", arr1+arr2)

#element wise substraction
print("Substraction: ", arr1 - arr2)

Addition:  [11 22 33 44 55]
Substraction:  [ -9 -18 -27 -36 -45]


Universal Function that applies to the entire array

In [10]:
arr = np.array([1,2,3,4,5])
print(np.sqrt(arr))

# we can do for sin, natural log etc

[1.         1.41421356 1.73205081 2.         2.23606798]


Array Slicing and Indexing

In [11]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n", arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
# Fetch 1
print(arr[0][0])
print()
# Fetch 7,8,11,12
print(arr[1:,2:])
print()
# Fetch 3 4 7 8 
print(arr[0:2, 2:])
print()

# Fetch 6 7 10 11
print(arr[1:, 1:3])

1

[[ 7  8]
 [11 12]]

[[3 4]
 [7 8]]

[[ 6  7]
 [10 11]]


Modify Elements

In [13]:
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


### Normalization -  mean is 0 and standard deviation is 1

In [14]:
data = np.array([1,2,3,4,5])

# calculate mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


### Logical Operation

In [15]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])